export const API_KEY = `${process.env.REACT_APP_YOUTUBE_API_KEY}`;
export const FETCH_VIDEOS_BY_CHANNEL_ID = "FETCH_VIDEOS_BY_CHANNEL_ID";
export const FETCH_VIDEOS_BY_MOST_POPULAR = "FETCH_VIDEOS_BY_MOST_POPULAR";
export const FETCH_VIDEO_BY_ID = "FETCH_VIDEO_BY_ID";
export const FETCH_VIDEOS = "FETCH_VIDEOS";
export const FETCH_CHANNEL = "FETCH_CHANNEL";
export const FETCH_RELATED = "FETCH_RELATED";
